---
title: "Shumai User Interest Profiling"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows #def columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include = FALSE}
source("../setup.R")
source("../analysis.R")
source("../support.R")
values <- reactiveValues()
```


Setup
=====================================

-----------------------------------------------------------------------

### Setup Window
Please retrieve the user database first.
```{r echo = FALSE}
hr()
textInput("db.get.link", label = h3("DB Link"), value = "pumi-4-1.tddc88-2018.ida.liu.se:8085/api/user")
actionButton("buttonGetDB", "Fetch User Database")

#fetchDB <- eventReactive(input$buttonGetDB, {
observeEvent(input$buttonGetDB,  {
  print("buttonGetDB pressed")
  channel.df <- ImportJSON(input$db.get.link)
  values$raw.data <- channel.df
  #print(colnames(values$raw.data))
})

hr()
```

Trends
=====================================
Settings {.sidebar}
-----------------------------------------------------------------------
#### Time period
Select the time period to analyze.
```{r echo = FALSE}
dateRangeInput('dateRange',
      label = 'Date range input: yyyy-mm-dd',
      start = Sys.Date() - 7, end = Sys.Date(),
      max = Sys.Date()
    )

observeEvent(input$dateRange, {
  #print(str(input$dateRange))
  if (!is.null(values$raw.data)) {
    values$filtered.view.data <- CountViewsByDates(values$raw.data, input$dateRange)
    #print(values$filtered.view.data)
    values$normalized.data <- NormalizeData(values$filtered.view.data)
    #print(values$normalized.data)
  }
  },
  ignoreInit = TRUE
  )
```

#### Categories
```{r}
category.list.names <- c("Animals", "Cars", "Celeb", "Comedy & Entertainment", "Creative", "Education", "Gaming", "Kids", "Lifestyle & How-to", "Movies", "Music", "News", "Sports", "Tech", "Travel", "TV", "Webcam")
category.list.id <- c("animals", "auto", "people", "fun", "creation", "school", "videogames", "kids", "lifestyle", "shortfilms", "music", "news", "sport", "tech", "travel", "tv", "webcam")

# slidersUI <- function(id) {
#   fluidRow(
#       lapply(seq(category.list.id), function(i) {
#       sliderInput(inputId = paste0("range.", category.list.id[i]),
#       label = category.list.names[i],
#       min = 0, max = 1, value = c(0, 1))
#     })
#   )
# }
# slidersUI("slide")

#Ctrl + Shift + C för att kommentera block
sliderInput(inputId = "range.animals", label = category.list.names[1],
            min = 0, max = 1, value = c(0, 1))
sliderInput(inputId = "range.auto", label = category.list.names[2],
            min = 0, max = 1, value = c(0, 1))
sliderInput(inputId = "range.people", label = category.list.names[3],
            min = 0, max = 1, value = c(0, 1))
sliderInput(inputId = "range.fun", label = category.list.names[4],
            min = 0, max = 1, value = c(0, 1))
sliderInput(inputId = "range.creation", label = category.list.names[5],
            min = 0, max = 1, value = c(0, 1))
sliderInput(inputId = "range.school", label = category.list.names[6],
            min = 0, max = 1, value = c(0, 1))
sliderInput(inputId = "range.videogames", label = category.list.names[7],
            min = 0, max = 1, value = c(0, 1))
sliderInput(inputId = "range.kids", label = category.list.names[8],
            min = 0, max = 1, value = c(0, 1))
sliderInput(inputId = "range.lifestyle", label = category.list.names[9],
            min = 0, max = 1, value = c(0, 1))
sliderInput(inputId = "range.shortfilms", label = category.list.names[10],
            min = 0, max = 1, value = c(0, 1))
sliderInput(inputId = "range.music", label = category.list.names[11],
            min = 0, max = 1, value = c(0, 1))
sliderInput(inputId = "range.news", label = category.list.names[12],
            min = 0, max = 1, value = c(0, 1))
sliderInput(inputId = "range.sport", label = category.list.names[13],
            min = 0, max = 1, value = c(0, 1))
sliderInput(inputId = "range.tech", label = category.list.names[14],
            min = 0, max = 1, value = c(0, 1))
sliderInput(inputId = "range.travel", label = category.list.names[15],
            min = 0, max = 1, value = c(0, 1))
sliderInput(inputId = "range.tv", label = category.list.names[16],
            min = 0, max = 1, value = c(0, 1))
sliderInput(inputId = "range.webcam", label = category.list.names[17],
            min = 0, max = 1, value = c(0, 1))
hr()

sliderValues <- reactive({
  c(input$range.animals, input$range.auto, input$range.people,
    input$range.fun, input$range.creation, input$range.school,
    input$range.videogames, input$range.kids, input$range.lifestyle,
    input$range.shortfilms, input$range.music, input$range.news,
    input$range.sport, input$range.tech, input$range.travel,
    input$range.tv, input$range.webcam)
})
```

```{r}
actionButton("buttonApplyFilter", "Filter users")

br()
```


#### Export
```{r}
# TODO
#renderUI({
  downloadButton("buttonPrint", "Download user list")
#})

downloadHandler(filename = function() {
  return(paste("users", ".csv"))
}, 
  content = function(file) {
    #to_save <- dataInput()
    write.csv(as.data.frame(dataInput()), "users.csv", "text/csv")
  }
)

# shinyApp( # NOT WORKING
#   ui <- fillPage(
#     inputPanel(
#       downloadButton("buttonExportFilteredUsers", "Export current filtering")
#     )
#   ),
#   
#   server <- function(input, output) {
#     output$buttonExportFilteredUsers <- downloadHandler(
#       filename = function() {
#         #paste("Filtered users", Sys.Date(), ".csv", sep = "")
#         "hej.csv"
#       },
#       content = function(file) {
#         write.csv(values@raw.data, file)
#       }
#     )
#   }
# )
hr()
```


Row
-----------------------------------------------------------------------

### Unique users {.value-box}
```{r}
# total.user.count is a reactive expression that keeps an approximate
# count of all of the unique users that have been seen since the
# app started. Includes the default user.
renderValueBox({
  total.user.count <- nrow(values$filtered.view.data)
  valueBox(value = total.user.count, icon = "glyphicon-user")
})
```

### Total video views {.value-box}
```{r}
renderValueBox({
  total.view.count <- sum(values$filtered.view.data) #TODO
  valueBox(value = total.view.count, icon = "glyphicon-play")
})
```


### Most popular category {.value-box}
```{r}
renderValueBox({
  # TODO: Call function()
  valueBox(value = "Memes", color = "Green", icon = "glyphicon-thumbs-up")
})
```

### Least popular category {.value-box}
```{r}
renderValueBox({
  # TODO: Call function()
  valueBox(value = "News", color = "Maroon", icon = "glyphicon-thumbs-down")
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart Ridge
```{r}
#print("Ggridge")
ridgeInput <- reactive({
  values$normalized.data
})

renderPlot({
  #print(str(values$normalized.data))
  #print(values$normalized.data)
    if (!is.null(ridgeInput())) {
      print(ridgeInput())
      #print(stack(as.data.frame(ridgeInput())))
      print(sliderValues())
      
      ggplot(stack(as.data.frame(ridgeInput())), aes(x = values, y = ind)) +
        geom_density_ridges(aes(group = ind, color = ind), alpha = 0.3) +
        scale_x_continuous(limits=c(0, 1))

      #ggplot(as.data.frame(ridgeInput()), aes(x = values, y = ind)) +
      #  geom_density_ridges(aes(group = ind, color = ind), alpha = 0.3)
    }
})
```